# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/agentic-rag',
                'doc_host': 'https://shacholle.github.io',
                'git_url': 'https://github.com/shacholle/agentic-rag',
                'lib_path': 'agentic_rag'},
  'syms': {'agentic_rag.core': {'agentic_rag.core.connect_agent': ('core.html#connect_agent', 'agentic_rag/core.py')}}}
