# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['connect_agent']

# %% ../nbs/00_core.ipynb 4
def connect_agent(agent):
    "Connect to agent"
    return f'Connected to {agent}!'
